//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("cat.csv ver:0.9.30929.1")]
[assembly: AssemblyDescription("cat.csv")]
[assembly: AssemblyProduct("cat.csv")]
[assembly: AssemblyCopyright("Copyright (C) 2003-2013 Kody Brown.")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("63FE1513-B06A-4D5D-B814-FC5EF155BE3C")]
[assembly: AssemblyVersion("0.9.30929.1")]
[assembly: AssemblyFileVersion("0.9.30929.1")]


